on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

permissions: read-all

jobs:
  build-deploy:
    runs-on: ubunto-latest
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker compose build -t ${{ secrets.DOCKER_USERNAME }}/scd:latest

      - name: Push Docker images
        run: |
          docker-compose push
